url: "https://www.schafe-vorm-fenster.org/"
baseurl: ""
title: "Projektb√ºro Schafe vorm Fenter UG"
collections:
  references:
    output: false
  visions:
    output: false
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
exclude:
  - package.json
  - yarn.lock
  - tailwind.config.js
  - postcss.config.js
  - tailwindcss*
  - README.md
