url: "https://www.schafe-vorm-fenster.org/"
baseurl: ""
title: "Projektb√ºro Schafe vorm Fenter UG"
collections:
  references:
    output: false
  visions:
    output: false
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
plugins:
  - jekyll-postcss
sass:
  load_paths:
    - _sass
    - node_modules
postcss:
  cache: false
include: ["node_modules/tailwindcss"]
exclude:
  - package.json
  - yarn.lock
  - tailwind.config.js
  - postcss.config.js
